config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :artists, only: %i[index show new create]
  resources :albums
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :user
  has_many :artists

   # belongs_to :artist

  validates :album_name, :year, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :albums
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :albums
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :authentication_keys => [:username]

  validates :username, uniqueness: true
  validates :fullname, presence: true
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
    before_action :set_album, only: %i[ show edit update destroy]

  # GET /albums
  def index
    @albums = Album.includes(:user) # aumentando a velocidade de uma querry no sql

  end

  # GET
  def show
    @albums = Album.find(params[:id])
    @artist = Artist.find(params[:id])
  end

  # GET
  def new
    @album = Album.new
    @artists = Artist.all
  end

  # GET /albums/1/edit
  def edit
    @album = Album.find(params[:id])
    @artist = Artist.all
  end

  # POST
  def create
    @album = Album.new(album_params)
    @album.user = current_user
   # @album.artist = Artists.select(params[:name])
    if @album.save
      redirect_to @album
    else
      render :new
    end
  end

  def update
    if where_modification?
      if @album.update(album_params)
        redirect_to @album, notice: 'Album was successfully dupdated'
      else
        render :edit
      end
    else
      redirect_to @album, notice: 'Action Forbidden'
    end
  end

  # DELETE
  def destroy
    if current_user.admin
      @album.destroy
      redirect_to albums_url, notice: 'Album was successfully destroyed'
    else
      redirect_to albums_path, notice: 'Action Forbidden'
    end
  end

  private
    # callbacks
    def set_album
      @album = Album.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def album_params
      params.require(:album).permit(:album_name, :year, :user_id, :artist_id)
    end

    def where_modification?
      @album.user == current_user
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    artists_path
  end

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :fullname, :password, :password_confirmation]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: [:username, :password]
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: %i[show edit update]

  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
  end

  def new
    @artist = Artist.new
  end

  # POST
  def create
    @artist = Artist.new(artist_params)
  end

  private
  def set_artist
    @artist = Artist.find(params[:id])
  end

  def artist_params
    params.require(:artist).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/_form.html.erb
<div class = "container">
  <%= simple_form_for(@album) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <div class="col-md-6 col-sm-6 col-xs-12 form-inputs mb-2 radius-15" >
        <%= f.collection_select :artist_id, Artist.order(:name), :id, :name, include_blank: true %>
        <%= f.input :album_name %>
        <%= f.input :year %>
        <% f.association :user %>
      </div>
    </div>

    <div class="form-actions">
      <button type="button" class="btn btn-success btn-sm">
        <%= f.button :submit %>
      </button>
    </div>
  <% end %>
</div>

app/views/albums/edit.html.erb
<div class="container">
<h1>Editing Album</h1>

 <%= simple_form_for(@album) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <div class="col-md-6 col-sm-6 col-xs-12 form-inputs mb-2 radius-15" >

        <%= f.input :album_name %>
        <%= f.input :year %>
        <% f.association :user %>
      </div>
    </div>

    <div class="form-actions">
      <button type="button" class="btn btn-success btn-sm">
        <%= f.button :submit %>
      </button>
    </div>
  <% end %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>
</div>

app/views/albums/index.html.erb
<div class = "container">
  <p id="notice"><%= notice %></p>

  <h1>Albums</h1>

  <table>
    <div class="col-md-6 col-sm-6 col-xs-12 form-inputs mb-2 radius-15" >
      <thead>
        <tr>
          <th>Album name</th>
          <th>Year</th>
          <th>Created by</th>

        </tr>
      </thead>

      <tbody>
        <% @albums.each do |album| %>
          <tr>

            <td><%= album.album_name %></td>
            <td ><%= album.year %></td>
            <td><%= album.user.username %></td>
            <td>
              <button type="button" class="btn btn-success"><%= link_to 'Show', album %></button>
            </td>
            <td>
            <button type="button" class="btn btn-warning"><%= link_to 'Edit', edit_album_path(album) %></button>
            </td>
            <% if  current_user.admin %>
              <td>
              <button type="button" class="btn btn-danger"><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></button>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </div>
  </table>

  <br>
  <button type="button" class="btn btn-outline-primary"><%= link_to 'New Album', new_album_path %></button>
  <button type="button" class="btn btn-dark"><%= link_to 'Back', artists_path %></button>
  <%= render 'shared/flashes'%>
</div>

app/views/albums/new.html.erb
<div class = "container">
  <h1>New Album</h1>

  <%= render 'form', album: @album %>

  <button type="button" class="btn btn-outline-warning btn-sm">
      <%= link_to 'Back', albums_path %>
  </button>
<%= render 'shared/flashes'%>
</div>

app/views/albums/show.html.erb
<div class="container">

  <p>
    <strong>Artist:</strong>
    <%= @artist.name %>
  </p>

  <p>
    <strong>Album name:</strong>
    <%= @album.album_name %>
  </p>

  <p>
    <strong>Year:</strong>
    <%= @album.year %>
  </p>


  <button type="button" class="btn btn-warning"><%= link_to 'Edit', edit_album_path(@album) %></button>
  <button type="button" class="btn btn-dark"><%= link_to 'Back', albums_path %></button>

  <%= render 'shared/flashes'%>
</div>

app/views/artists/index.html.erb
<div class ='container'>
  <tbody>
    <%= link_to 'Create your album', albums_path, class: "btn btn-outline-dark btn-sm radius-15" %>

    <% @artists.each do |artist| %>
      <ul>
        <li><%= artist.name %></li>
      </ul>
    <% end %>

  </tbody>
</div>

app/views/artists/show.html.erb
<p>
  <strong>Artist Name:</strong>
  <%= @artist.name %>
</p>
<%= link_to 'Back', albums_path %>
<%= render 'shared/flashes'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoatBuildersTask</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Albums", albums_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Artists", artists_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://pbs.twimg.com/profile_images/1333399719016587265/o17x0ZqP_400x400.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>